[project]
name = "fwriter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HecurH", email = "hecker@hecur.ru" }
]
requires-python = ">=3.14.7"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "httpx>=0.28.1",
    "keyring>=25.7.0",
    "platformdirs>=4.11.2",
    "textual>=8.2.8",
]

[project.scripts]
fwriter = "fwriter.run:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.2",
    "textual-dev>=1.8.0",
]
